### ISSUE TITLE
Monochrome  display

### ISSUE THREAD

**Issue by alex2root** [awigen/ExpressLRS#4]
I have a TX12 transmitter, there is no gyroscope settings menu ((((

That is how it should be ?

**Comment by pfeerick** [comment]
Where are you going to configure it? Did you, in the ExpressLRS lua, go down to Other Devices -> Your RX name (i.e. BFPV 14CH P2G4)? You should have `Gyro Modes`, `Gyro Gains` and `Gyro Settings` options there, amongst others... 

![image](https://github.com/user-attachments/assets/ec20bd36-1de8-4b60-99c8-3efb00475e25)

**Comment by awigen** [comment]
@pfeerick explained how this is supposed to work, I've tested this with both color TX16s and monochrome pocket radios. Closing. Feel free to ask on Discord if you need any assistance https://discord.com/channels/596350022191415318/1135438746016292914
